# Generated by Django 6.0.3 on 2026-07-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_module', '0002_question_created_at_question_explanation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcategory',
            name='name',
            field=models.CharField(choices=[('aptitude', 'Aptitude'), ('behavioral', 'behavioral'), ('hr', 'HR'), ('coding', 'Coding')], max_length=20, unique=True),
        ),
    ]
