# Generated by Django 5.0.6 on 2026-07-04 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_name', models.CharField(blank=True, max_length=150)),
                ('extracted_email', models.CharField(blank=True, max_length=150)),
                ('extracted_phone', models.CharField(blank=True, max_length=50)),
                ('extracted_skills', models.TextField(blank=True)),
                ('extracted_education', models.TextField(blank=True)),
                ('extracted_projects', models.TextField(blank=True)),
                ('raw_text', models.TextField(blank=True)),
                ('resume_score', models.FloatField(default=0)),
                ('suggestions', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
